backend:
  name: test-repo

media_folder: static/assets
public_foler: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields: 
      - { name: path, label: path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: title }
      - { name: body, label: Body, widget: markdown }